# Generated by Django 4.0.6 on 2022-07-18 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organizatsion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Organizatsion name')),
                ('description', models.CharField(max_length=264, null=True, verbose_name='Description for org')),
                ('phone', models.CharField(max_length=13, verbose_name='phone number')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logo/')),
            ],
        ),
        migrations.CreateModel(
            name='partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Partners name')),
                ('last_name', models.CharField(max_length=64, verbose_name='Partners last name')),
                ('phone', models.CharField(max_length=13, verbose_name='phone number')),
                ('description', models.CharField(max_length=264, null=True, verbose_name='Description for org')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='User name')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=16)),
                ('role', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Room name')),
                ('oraganizatsion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organizatsion', verbose_name='Which organizatsion')),
            ],
        ),
        migrations.CreateModel(
            name='platform_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64, verbose_name='co-worker name')),
                ('phone', models.CharField(max_length=13, verbose_name='phone number')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=16, unique=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'director'), (2, 'manager'), (3, 'waiter')], verbose_name='wat role')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organizatsion')),
            ],
        ),
        migrations.AddField(
            model_name='organizatsion',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.partner', verbose_name='Director'),
        ),
        migrations.CreateModel(
            name='organization_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Table numbers')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.room')),
            ],
        ),
    ]
