# Generated by Django 4.0.6 on 2022-08-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_category_photo_product_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='organization',
        ),
    ]
