# Generated by Django 4.0.6 on 2022-09-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product_view',
        ),
    ]
