# Generated by Django 4.0.6 on 2022-09-05 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_view',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 12, 22, 36, 930366)),
        ),
    ]
