# Generated by Django 4.0.6 on 2022-09-05 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_product_view_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_view',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 15, 33, 48, 175200)),
        ),
    ]
