# Generated by Django 4.0.6 on 2022-09-07 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_view_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_view',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 11, 36, 37, 946642)),
        ),
    ]
