# Generated by Django 4.0.6 on 2022-09-07 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_product_count_alter_product_view_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_view',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 18, 36, 16, 459643)),
        ),
    ]
