# Generated by Django 4.0.6 on 2022-09-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_view_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product_view',
        ),
    ]
