# Generated by Django 4.0.6 on 2022-09-13 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_amount_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_amount',
            name='amount',
        ),
    ]
