# Generated by Django 4.0.6 on 2022-09-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_remove_product_amount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_amount',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Item title'),
        ),
    ]
