# Generated by Django 4.0.6 on 2022-07-18 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_number', models.PositiveSmallIntegerField(help_text='How many clients', verbose_name='Peopls')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'new'), (2, 'pending'), (3, 'preparing'), (4, 'cancellation')], verbose_name='Order status')),
                ('paymants', models.PositiveSmallIntegerField(choices=[(1, 'Cash'), (2, 'Terminal'), (3, 'PayMe'), (4, 'Click')], verbose_name='Paymants')),
                ('organization_table', models.ForeignKey(help_text='Which table the client chose', on_delete=django.db.models.deletion.PROTECT, to='organization.organization_table', verbose_name='table number')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product_amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product_amount')),
            ],
        ),
    ]
