# Generated by Django 4.0.6 on 2022-08-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'new'), (2, 'pending'), (3, 'preparing'), (4, 'cancellation')], default=1, verbose_name='Order status'),
        ),
    ]
